outputDir: public
title: Brian Greenhill
description: Site Reliability Engineer at GitHub
github: https://github.com/BrianGreenhill
contentDir: content
author: Brian Greenhill
authorImg: https://avatars.githubusercontent.com/u/1642339?v=4
linkedin: https://www.linkedin.com/in/briangree
email: brian@briangreenhill.net
theme: default
